/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinksRouteImport } from './routes/links'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PurpleRouteRouteImport } from './routes/purple/route'
import { Route as M209RouteRouteImport } from './routes/m209/route'
import { Route as EnigmaRouteRouteImport } from './routes/enigma/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PurpleOperateRouteImport } from './routes/purple/operate'
import { Route as PurpleAboutRouteImport } from './routes/purple/about'
import { Route as M209OperateRouteImport } from './routes/m209/operate'
import { Route as M209AboutRouteImport } from './routes/m209/about'
import { Route as EnigmaOperateRouteImport } from './routes/enigma/operate'
import { Route as EnigmaAboutRouteImport } from './routes/enigma/about'
import { Route as PurpleSetupRouteRouteImport } from './routes/purple/setup/route'
import { Route as M209SetupRouteRouteImport } from './routes/m209/setup/route'
import { Route as EnigmaSetupRouteRouteImport } from './routes/enigma/setup/route'
import { Route as PurpleSetupSwitchesRouteImport } from './routes/purple/setup/switches'
import { Route as PurpleSetupPlugboardRouteImport } from './routes/purple/setup/plugboard'
import { Route as M209SetupWheelsRouteImport } from './routes/m209/setup/wheels'
import { Route as M209SetupDrumRouteImport } from './routes/m209/setup/drum'
import { Route as EnigmaSetupRotorsRouteImport } from './routes/enigma/setup/rotors'
import { Route as EnigmaSetupRingsRouteImport } from './routes/enigma/setup/rings'
import { Route as EnigmaSetupPlugboardRouteImport } from './routes/enigma/setup/plugboard'
import { Route as EnigmaSetupModelRouteImport } from './routes/enigma/setup/model'

const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PurpleRouteRoute = PurpleRouteRouteImport.update({
  id: '/purple',
  path: '/purple',
  getParentRoute: () => rootRouteImport,
} as any)
const M209RouteRoute = M209RouteRouteImport.update({
  id: '/m209',
  path: '/m209',
  getParentRoute: () => rootRouteImport,
} as any)
const EnigmaRouteRoute = EnigmaRouteRouteImport.update({
  id: '/enigma',
  path: '/enigma',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurpleOperateRoute = PurpleOperateRouteImport.update({
  id: '/operate',
  path: '/operate',
  getParentRoute: () => PurpleRouteRoute,
} as any)
const PurpleAboutRoute = PurpleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PurpleRouteRoute,
} as any)
const M209OperateRoute = M209OperateRouteImport.update({
  id: '/operate',
  path: '/operate',
  getParentRoute: () => M209RouteRoute,
} as any)
const M209AboutRoute = M209AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => M209RouteRoute,
} as any)
const EnigmaOperateRoute = EnigmaOperateRouteImport.update({
  id: '/operate',
  path: '/operate',
  getParentRoute: () => EnigmaRouteRoute,
} as any)
const EnigmaAboutRoute = EnigmaAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnigmaRouteRoute,
} as any)
const PurpleSetupRouteRoute = PurpleSetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PurpleRouteRoute,
} as any)
const M209SetupRouteRoute = M209SetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => M209RouteRoute,
} as any)
const EnigmaSetupRouteRoute = EnigmaSetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => EnigmaRouteRoute,
} as any)
const PurpleSetupSwitchesRoute = PurpleSetupSwitchesRouteImport.update({
  id: '/switches',
  path: '/switches',
  getParentRoute: () => PurpleSetupRouteRoute,
} as any)
const PurpleSetupPlugboardRoute = PurpleSetupPlugboardRouteImport.update({
  id: '/plugboard',
  path: '/plugboard',
  getParentRoute: () => PurpleSetupRouteRoute,
} as any)
const M209SetupWheelsRoute = M209SetupWheelsRouteImport.update({
  id: '/wheels',
  path: '/wheels',
  getParentRoute: () => M209SetupRouteRoute,
} as any)
const M209SetupDrumRoute = M209SetupDrumRouteImport.update({
  id: '/drum',
  path: '/drum',
  getParentRoute: () => M209SetupRouteRoute,
} as any)
const EnigmaSetupRotorsRoute = EnigmaSetupRotorsRouteImport.update({
  id: '/rotors',
  path: '/rotors',
  getParentRoute: () => EnigmaSetupRouteRoute,
} as any)
const EnigmaSetupRingsRoute = EnigmaSetupRingsRouteImport.update({
  id: '/rings',
  path: '/rings',
  getParentRoute: () => EnigmaSetupRouteRoute,
} as any)
const EnigmaSetupPlugboardRoute = EnigmaSetupPlugboardRouteImport.update({
  id: '/plugboard',
  path: '/plugboard',
  getParentRoute: () => EnigmaSetupRouteRoute,
} as any)
const EnigmaSetupModelRoute = EnigmaSetupModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => EnigmaSetupRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enigma': typeof EnigmaRouteRouteWithChildren
  '/m209': typeof M209RouteRouteWithChildren
  '/purple': typeof PurpleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/links': typeof LinksRoute
  '/enigma/setup': typeof EnigmaSetupRouteRouteWithChildren
  '/m209/setup': typeof M209SetupRouteRouteWithChildren
  '/purple/setup': typeof PurpleSetupRouteRouteWithChildren
  '/enigma/about': typeof EnigmaAboutRoute
  '/enigma/operate': typeof EnigmaOperateRoute
  '/m209/about': typeof M209AboutRoute
  '/m209/operate': typeof M209OperateRoute
  '/purple/about': typeof PurpleAboutRoute
  '/purple/operate': typeof PurpleOperateRoute
  '/enigma/setup/model': typeof EnigmaSetupModelRoute
  '/enigma/setup/plugboard': typeof EnigmaSetupPlugboardRoute
  '/enigma/setup/rings': typeof EnigmaSetupRingsRoute
  '/enigma/setup/rotors': typeof EnigmaSetupRotorsRoute
  '/m209/setup/drum': typeof M209SetupDrumRoute
  '/m209/setup/wheels': typeof M209SetupWheelsRoute
  '/purple/setup/plugboard': typeof PurpleSetupPlugboardRoute
  '/purple/setup/switches': typeof PurpleSetupSwitchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enigma': typeof EnigmaRouteRouteWithChildren
  '/m209': typeof M209RouteRouteWithChildren
  '/purple': typeof PurpleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/links': typeof LinksRoute
  '/enigma/setup': typeof EnigmaSetupRouteRouteWithChildren
  '/m209/setup': typeof M209SetupRouteRouteWithChildren
  '/purple/setup': typeof PurpleSetupRouteRouteWithChildren
  '/enigma/about': typeof EnigmaAboutRoute
  '/enigma/operate': typeof EnigmaOperateRoute
  '/m209/about': typeof M209AboutRoute
  '/m209/operate': typeof M209OperateRoute
  '/purple/about': typeof PurpleAboutRoute
  '/purple/operate': typeof PurpleOperateRoute
  '/enigma/setup/model': typeof EnigmaSetupModelRoute
  '/enigma/setup/plugboard': typeof EnigmaSetupPlugboardRoute
  '/enigma/setup/rings': typeof EnigmaSetupRingsRoute
  '/enigma/setup/rotors': typeof EnigmaSetupRotorsRoute
  '/m209/setup/drum': typeof M209SetupDrumRoute
  '/m209/setup/wheels': typeof M209SetupWheelsRoute
  '/purple/setup/plugboard': typeof PurpleSetupPlugboardRoute
  '/purple/setup/switches': typeof PurpleSetupSwitchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enigma': typeof EnigmaRouteRouteWithChildren
  '/m209': typeof M209RouteRouteWithChildren
  '/purple': typeof PurpleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/links': typeof LinksRoute
  '/enigma/setup': typeof EnigmaSetupRouteRouteWithChildren
  '/m209/setup': typeof M209SetupRouteRouteWithChildren
  '/purple/setup': typeof PurpleSetupRouteRouteWithChildren
  '/enigma/about': typeof EnigmaAboutRoute
  '/enigma/operate': typeof EnigmaOperateRoute
  '/m209/about': typeof M209AboutRoute
  '/m209/operate': typeof M209OperateRoute
  '/purple/about': typeof PurpleAboutRoute
  '/purple/operate': typeof PurpleOperateRoute
  '/enigma/setup/model': typeof EnigmaSetupModelRoute
  '/enigma/setup/plugboard': typeof EnigmaSetupPlugboardRoute
  '/enigma/setup/rings': typeof EnigmaSetupRingsRoute
  '/enigma/setup/rotors': typeof EnigmaSetupRotorsRoute
  '/m209/setup/drum': typeof M209SetupDrumRoute
  '/m209/setup/wheels': typeof M209SetupWheelsRoute
  '/purple/setup/plugboard': typeof PurpleSetupPlugboardRoute
  '/purple/setup/switches': typeof PurpleSetupSwitchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enigma'
    | '/m209'
    | '/purple'
    | '/about'
    | '/links'
    | '/enigma/setup'
    | '/m209/setup'
    | '/purple/setup'
    | '/enigma/about'
    | '/enigma/operate'
    | '/m209/about'
    | '/m209/operate'
    | '/purple/about'
    | '/purple/operate'
    | '/enigma/setup/model'
    | '/enigma/setup/plugboard'
    | '/enigma/setup/rings'
    | '/enigma/setup/rotors'
    | '/m209/setup/drum'
    | '/m209/setup/wheels'
    | '/purple/setup/plugboard'
    | '/purple/setup/switches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enigma'
    | '/m209'
    | '/purple'
    | '/about'
    | '/links'
    | '/enigma/setup'
    | '/m209/setup'
    | '/purple/setup'
    | '/enigma/about'
    | '/enigma/operate'
    | '/m209/about'
    | '/m209/operate'
    | '/purple/about'
    | '/purple/operate'
    | '/enigma/setup/model'
    | '/enigma/setup/plugboard'
    | '/enigma/setup/rings'
    | '/enigma/setup/rotors'
    | '/m209/setup/drum'
    | '/m209/setup/wheels'
    | '/purple/setup/plugboard'
    | '/purple/setup/switches'
  id:
    | '__root__'
    | '/'
    | '/enigma'
    | '/m209'
    | '/purple'
    | '/about'
    | '/links'
    | '/enigma/setup'
    | '/m209/setup'
    | '/purple/setup'
    | '/enigma/about'
    | '/enigma/operate'
    | '/m209/about'
    | '/m209/operate'
    | '/purple/about'
    | '/purple/operate'
    | '/enigma/setup/model'
    | '/enigma/setup/plugboard'
    | '/enigma/setup/rings'
    | '/enigma/setup/rotors'
    | '/m209/setup/drum'
    | '/m209/setup/wheels'
    | '/purple/setup/plugboard'
    | '/purple/setup/switches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnigmaRouteRoute: typeof EnigmaRouteRouteWithChildren
  M209RouteRoute: typeof M209RouteRouteWithChildren
  PurpleRouteRoute: typeof PurpleRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LinksRoute: typeof LinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purple': {
      id: '/purple'
      path: '/purple'
      fullPath: '/purple'
      preLoaderRoute: typeof PurpleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m209': {
      id: '/m209'
      path: '/m209'
      fullPath: '/m209'
      preLoaderRoute: typeof M209RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enigma': {
      id: '/enigma'
      path: '/enigma'
      fullPath: '/enigma'
      preLoaderRoute: typeof EnigmaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purple/operate': {
      id: '/purple/operate'
      path: '/operate'
      fullPath: '/purple/operate'
      preLoaderRoute: typeof PurpleOperateRouteImport
      parentRoute: typeof PurpleRouteRoute
    }
    '/purple/about': {
      id: '/purple/about'
      path: '/about'
      fullPath: '/purple/about'
      preLoaderRoute: typeof PurpleAboutRouteImport
      parentRoute: typeof PurpleRouteRoute
    }
    '/m209/operate': {
      id: '/m209/operate'
      path: '/operate'
      fullPath: '/m209/operate'
      preLoaderRoute: typeof M209OperateRouteImport
      parentRoute: typeof M209RouteRoute
    }
    '/m209/about': {
      id: '/m209/about'
      path: '/about'
      fullPath: '/m209/about'
      preLoaderRoute: typeof M209AboutRouteImport
      parentRoute: typeof M209RouteRoute
    }
    '/enigma/operate': {
      id: '/enigma/operate'
      path: '/operate'
      fullPath: '/enigma/operate'
      preLoaderRoute: typeof EnigmaOperateRouteImport
      parentRoute: typeof EnigmaRouteRoute
    }
    '/enigma/about': {
      id: '/enigma/about'
      path: '/about'
      fullPath: '/enigma/about'
      preLoaderRoute: typeof EnigmaAboutRouteImport
      parentRoute: typeof EnigmaRouteRoute
    }
    '/purple/setup': {
      id: '/purple/setup'
      path: '/setup'
      fullPath: '/purple/setup'
      preLoaderRoute: typeof PurpleSetupRouteRouteImport
      parentRoute: typeof PurpleRouteRoute
    }
    '/m209/setup': {
      id: '/m209/setup'
      path: '/setup'
      fullPath: '/m209/setup'
      preLoaderRoute: typeof M209SetupRouteRouteImport
      parentRoute: typeof M209RouteRoute
    }
    '/enigma/setup': {
      id: '/enigma/setup'
      path: '/setup'
      fullPath: '/enigma/setup'
      preLoaderRoute: typeof EnigmaSetupRouteRouteImport
      parentRoute: typeof EnigmaRouteRoute
    }
    '/purple/setup/switches': {
      id: '/purple/setup/switches'
      path: '/switches'
      fullPath: '/purple/setup/switches'
      preLoaderRoute: typeof PurpleSetupSwitchesRouteImport
      parentRoute: typeof PurpleSetupRouteRoute
    }
    '/purple/setup/plugboard': {
      id: '/purple/setup/plugboard'
      path: '/plugboard'
      fullPath: '/purple/setup/plugboard'
      preLoaderRoute: typeof PurpleSetupPlugboardRouteImport
      parentRoute: typeof PurpleSetupRouteRoute
    }
    '/m209/setup/wheels': {
      id: '/m209/setup/wheels'
      path: '/wheels'
      fullPath: '/m209/setup/wheels'
      preLoaderRoute: typeof M209SetupWheelsRouteImport
      parentRoute: typeof M209SetupRouteRoute
    }
    '/m209/setup/drum': {
      id: '/m209/setup/drum'
      path: '/drum'
      fullPath: '/m209/setup/drum'
      preLoaderRoute: typeof M209SetupDrumRouteImport
      parentRoute: typeof M209SetupRouteRoute
    }
    '/enigma/setup/rotors': {
      id: '/enigma/setup/rotors'
      path: '/rotors'
      fullPath: '/enigma/setup/rotors'
      preLoaderRoute: typeof EnigmaSetupRotorsRouteImport
      parentRoute: typeof EnigmaSetupRouteRoute
    }
    '/enigma/setup/rings': {
      id: '/enigma/setup/rings'
      path: '/rings'
      fullPath: '/enigma/setup/rings'
      preLoaderRoute: typeof EnigmaSetupRingsRouteImport
      parentRoute: typeof EnigmaSetupRouteRoute
    }
    '/enigma/setup/plugboard': {
      id: '/enigma/setup/plugboard'
      path: '/plugboard'
      fullPath: '/enigma/setup/plugboard'
      preLoaderRoute: typeof EnigmaSetupPlugboardRouteImport
      parentRoute: typeof EnigmaSetupRouteRoute
    }
    '/enigma/setup/model': {
      id: '/enigma/setup/model'
      path: '/model'
      fullPath: '/enigma/setup/model'
      preLoaderRoute: typeof EnigmaSetupModelRouteImport
      parentRoute: typeof EnigmaSetupRouteRoute
    }
  }
}

interface EnigmaSetupRouteRouteChildren {
  EnigmaSetupModelRoute: typeof EnigmaSetupModelRoute
  EnigmaSetupPlugboardRoute: typeof EnigmaSetupPlugboardRoute
  EnigmaSetupRingsRoute: typeof EnigmaSetupRingsRoute
  EnigmaSetupRotorsRoute: typeof EnigmaSetupRotorsRoute
}

const EnigmaSetupRouteRouteChildren: EnigmaSetupRouteRouteChildren = {
  EnigmaSetupModelRoute: EnigmaSetupModelRoute,
  EnigmaSetupPlugboardRoute: EnigmaSetupPlugboardRoute,
  EnigmaSetupRingsRoute: EnigmaSetupRingsRoute,
  EnigmaSetupRotorsRoute: EnigmaSetupRotorsRoute,
}

const EnigmaSetupRouteRouteWithChildren =
  EnigmaSetupRouteRoute._addFileChildren(EnigmaSetupRouteRouteChildren)

interface EnigmaRouteRouteChildren {
  EnigmaSetupRouteRoute: typeof EnigmaSetupRouteRouteWithChildren
  EnigmaAboutRoute: typeof EnigmaAboutRoute
  EnigmaOperateRoute: typeof EnigmaOperateRoute
}

const EnigmaRouteRouteChildren: EnigmaRouteRouteChildren = {
  EnigmaSetupRouteRoute: EnigmaSetupRouteRouteWithChildren,
  EnigmaAboutRoute: EnigmaAboutRoute,
  EnigmaOperateRoute: EnigmaOperateRoute,
}

const EnigmaRouteRouteWithChildren = EnigmaRouteRoute._addFileChildren(
  EnigmaRouteRouteChildren,
)

interface M209SetupRouteRouteChildren {
  M209SetupDrumRoute: typeof M209SetupDrumRoute
  M209SetupWheelsRoute: typeof M209SetupWheelsRoute
}

const M209SetupRouteRouteChildren: M209SetupRouteRouteChildren = {
  M209SetupDrumRoute: M209SetupDrumRoute,
  M209SetupWheelsRoute: M209SetupWheelsRoute,
}

const M209SetupRouteRouteWithChildren = M209SetupRouteRoute._addFileChildren(
  M209SetupRouteRouteChildren,
)

interface M209RouteRouteChildren {
  M209SetupRouteRoute: typeof M209SetupRouteRouteWithChildren
  M209AboutRoute: typeof M209AboutRoute
  M209OperateRoute: typeof M209OperateRoute
}

const M209RouteRouteChildren: M209RouteRouteChildren = {
  M209SetupRouteRoute: M209SetupRouteRouteWithChildren,
  M209AboutRoute: M209AboutRoute,
  M209OperateRoute: M209OperateRoute,
}

const M209RouteRouteWithChildren = M209RouteRoute._addFileChildren(
  M209RouteRouteChildren,
)

interface PurpleSetupRouteRouteChildren {
  PurpleSetupPlugboardRoute: typeof PurpleSetupPlugboardRoute
  PurpleSetupSwitchesRoute: typeof PurpleSetupSwitchesRoute
}

const PurpleSetupRouteRouteChildren: PurpleSetupRouteRouteChildren = {
  PurpleSetupPlugboardRoute: PurpleSetupPlugboardRoute,
  PurpleSetupSwitchesRoute: PurpleSetupSwitchesRoute,
}

const PurpleSetupRouteRouteWithChildren =
  PurpleSetupRouteRoute._addFileChildren(PurpleSetupRouteRouteChildren)

interface PurpleRouteRouteChildren {
  PurpleSetupRouteRoute: typeof PurpleSetupRouteRouteWithChildren
  PurpleAboutRoute: typeof PurpleAboutRoute
  PurpleOperateRoute: typeof PurpleOperateRoute
}

const PurpleRouteRouteChildren: PurpleRouteRouteChildren = {
  PurpleSetupRouteRoute: PurpleSetupRouteRouteWithChildren,
  PurpleAboutRoute: PurpleAboutRoute,
  PurpleOperateRoute: PurpleOperateRoute,
}

const PurpleRouteRouteWithChildren = PurpleRouteRoute._addFileChildren(
  PurpleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnigmaRouteRoute: EnigmaRouteRouteWithChildren,
  M209RouteRoute: M209RouteRouteWithChildren,
  PurpleRouteRoute: PurpleRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LinksRoute: LinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
