/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PurpleRouteImport } from './routes/purple'
import { Route as M209RouteImport } from './routes/m209'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EnigmaRouteRouteImport } from './routes/enigma/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnigmaOperateRouteImport } from './routes/enigma/operate'
import { Route as EnigmaAboutRouteImport } from './routes/enigma/about'
import { Route as EnigmaSetupRouteRouteImport } from './routes/enigma/setup/route'
import { Route as EnigmaSetupRotorsRouteImport } from './routes/enigma/setup/rotors'
import { Route as EnigmaSetupRingsRouteImport } from './routes/enigma/setup/rings'
import { Route as EnigmaSetupPlugboardRouteImport } from './routes/enigma/setup/plugboard'
import { Route as EnigmaSetupModelRouteImport } from './routes/enigma/setup/model'

const PurpleRoute = PurpleRouteImport.update({
  id: '/purple',
  path: '/purple',
  getParentRoute: () => rootRouteImport,
} as any)
const M209Route = M209RouteImport.update({
  id: '/m209',
  path: '/m209',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnigmaRouteRoute = EnigmaRouteRouteImport.update({
  id: '/enigma',
  path: '/enigma',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnigmaOperateRoute = EnigmaOperateRouteImport.update({
  id: '/operate',
  path: '/operate',
  getParentRoute: () => EnigmaRouteRoute,
} as any)
const EnigmaAboutRoute = EnigmaAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnigmaRouteRoute,
} as any)
const EnigmaSetupRouteRoute = EnigmaSetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => EnigmaRouteRoute,
} as any)
const EnigmaSetupRotorsRoute = EnigmaSetupRotorsRouteImport.update({
  id: '/rotors',
  path: '/rotors',
  getParentRoute: () => EnigmaSetupRouteRoute,
} as any)
const EnigmaSetupRingsRoute = EnigmaSetupRingsRouteImport.update({
  id: '/rings',
  path: '/rings',
  getParentRoute: () => EnigmaSetupRouteRoute,
} as any)
const EnigmaSetupPlugboardRoute = EnigmaSetupPlugboardRouteImport.update({
  id: '/plugboard',
  path: '/plugboard',
  getParentRoute: () => EnigmaSetupRouteRoute,
} as any)
const EnigmaSetupModelRoute = EnigmaSetupModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => EnigmaSetupRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enigma': typeof EnigmaRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/m209': typeof M209Route
  '/purple': typeof PurpleRoute
  '/enigma/setup': typeof EnigmaSetupRouteRouteWithChildren
  '/enigma/about': typeof EnigmaAboutRoute
  '/enigma/operate': typeof EnigmaOperateRoute
  '/enigma/setup/model': typeof EnigmaSetupModelRoute
  '/enigma/setup/plugboard': typeof EnigmaSetupPlugboardRoute
  '/enigma/setup/rings': typeof EnigmaSetupRingsRoute
  '/enigma/setup/rotors': typeof EnigmaSetupRotorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enigma': typeof EnigmaRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/m209': typeof M209Route
  '/purple': typeof PurpleRoute
  '/enigma/setup': typeof EnigmaSetupRouteRouteWithChildren
  '/enigma/about': typeof EnigmaAboutRoute
  '/enigma/operate': typeof EnigmaOperateRoute
  '/enigma/setup/model': typeof EnigmaSetupModelRoute
  '/enigma/setup/plugboard': typeof EnigmaSetupPlugboardRoute
  '/enigma/setup/rings': typeof EnigmaSetupRingsRoute
  '/enigma/setup/rotors': typeof EnigmaSetupRotorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enigma': typeof EnigmaRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/m209': typeof M209Route
  '/purple': typeof PurpleRoute
  '/enigma/setup': typeof EnigmaSetupRouteRouteWithChildren
  '/enigma/about': typeof EnigmaAboutRoute
  '/enigma/operate': typeof EnigmaOperateRoute
  '/enigma/setup/model': typeof EnigmaSetupModelRoute
  '/enigma/setup/plugboard': typeof EnigmaSetupPlugboardRoute
  '/enigma/setup/rings': typeof EnigmaSetupRingsRoute
  '/enigma/setup/rotors': typeof EnigmaSetupRotorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enigma'
    | '/about'
    | '/m209'
    | '/purple'
    | '/enigma/setup'
    | '/enigma/about'
    | '/enigma/operate'
    | '/enigma/setup/model'
    | '/enigma/setup/plugboard'
    | '/enigma/setup/rings'
    | '/enigma/setup/rotors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enigma'
    | '/about'
    | '/m209'
    | '/purple'
    | '/enigma/setup'
    | '/enigma/about'
    | '/enigma/operate'
    | '/enigma/setup/model'
    | '/enigma/setup/plugboard'
    | '/enigma/setup/rings'
    | '/enigma/setup/rotors'
  id:
    | '__root__'
    | '/'
    | '/enigma'
    | '/about'
    | '/m209'
    | '/purple'
    | '/enigma/setup'
    | '/enigma/about'
    | '/enigma/operate'
    | '/enigma/setup/model'
    | '/enigma/setup/plugboard'
    | '/enigma/setup/rings'
    | '/enigma/setup/rotors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnigmaRouteRoute: typeof EnigmaRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  M209Route: typeof M209Route
  PurpleRoute: typeof PurpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/purple': {
      id: '/purple'
      path: '/purple'
      fullPath: '/purple'
      preLoaderRoute: typeof PurpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m209': {
      id: '/m209'
      path: '/m209'
      fullPath: '/m209'
      preLoaderRoute: typeof M209RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enigma': {
      id: '/enigma'
      path: '/enigma'
      fullPath: '/enigma'
      preLoaderRoute: typeof EnigmaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enigma/operate': {
      id: '/enigma/operate'
      path: '/operate'
      fullPath: '/enigma/operate'
      preLoaderRoute: typeof EnigmaOperateRouteImport
      parentRoute: typeof EnigmaRouteRoute
    }
    '/enigma/about': {
      id: '/enigma/about'
      path: '/about'
      fullPath: '/enigma/about'
      preLoaderRoute: typeof EnigmaAboutRouteImport
      parentRoute: typeof EnigmaRouteRoute
    }
    '/enigma/setup': {
      id: '/enigma/setup'
      path: '/setup'
      fullPath: '/enigma/setup'
      preLoaderRoute: typeof EnigmaSetupRouteRouteImport
      parentRoute: typeof EnigmaRouteRoute
    }
    '/enigma/setup/rotors': {
      id: '/enigma/setup/rotors'
      path: '/rotors'
      fullPath: '/enigma/setup/rotors'
      preLoaderRoute: typeof EnigmaSetupRotorsRouteImport
      parentRoute: typeof EnigmaSetupRouteRoute
    }
    '/enigma/setup/rings': {
      id: '/enigma/setup/rings'
      path: '/rings'
      fullPath: '/enigma/setup/rings'
      preLoaderRoute: typeof EnigmaSetupRingsRouteImport
      parentRoute: typeof EnigmaSetupRouteRoute
    }
    '/enigma/setup/plugboard': {
      id: '/enigma/setup/plugboard'
      path: '/plugboard'
      fullPath: '/enigma/setup/plugboard'
      preLoaderRoute: typeof EnigmaSetupPlugboardRouteImport
      parentRoute: typeof EnigmaSetupRouteRoute
    }
    '/enigma/setup/model': {
      id: '/enigma/setup/model'
      path: '/model'
      fullPath: '/enigma/setup/model'
      preLoaderRoute: typeof EnigmaSetupModelRouteImport
      parentRoute: typeof EnigmaSetupRouteRoute
    }
  }
}

interface EnigmaSetupRouteRouteChildren {
  EnigmaSetupModelRoute: typeof EnigmaSetupModelRoute
  EnigmaSetupPlugboardRoute: typeof EnigmaSetupPlugboardRoute
  EnigmaSetupRingsRoute: typeof EnigmaSetupRingsRoute
  EnigmaSetupRotorsRoute: typeof EnigmaSetupRotorsRoute
}

const EnigmaSetupRouteRouteChildren: EnigmaSetupRouteRouteChildren = {
  EnigmaSetupModelRoute: EnigmaSetupModelRoute,
  EnigmaSetupPlugboardRoute: EnigmaSetupPlugboardRoute,
  EnigmaSetupRingsRoute: EnigmaSetupRingsRoute,
  EnigmaSetupRotorsRoute: EnigmaSetupRotorsRoute,
}

const EnigmaSetupRouteRouteWithChildren =
  EnigmaSetupRouteRoute._addFileChildren(EnigmaSetupRouteRouteChildren)

interface EnigmaRouteRouteChildren {
  EnigmaSetupRouteRoute: typeof EnigmaSetupRouteRouteWithChildren
  EnigmaAboutRoute: typeof EnigmaAboutRoute
  EnigmaOperateRoute: typeof EnigmaOperateRoute
}

const EnigmaRouteRouteChildren: EnigmaRouteRouteChildren = {
  EnigmaSetupRouteRoute: EnigmaSetupRouteRouteWithChildren,
  EnigmaAboutRoute: EnigmaAboutRoute,
  EnigmaOperateRoute: EnigmaOperateRoute,
}

const EnigmaRouteRouteWithChildren = EnigmaRouteRoute._addFileChildren(
  EnigmaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnigmaRouteRoute: EnigmaRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  M209Route: M209Route,
  PurpleRoute: PurpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
